import photo from "../assets/Img/png/userImageMan.png";
import photoW from "../assets/Img/png/userImageWoman.png";

export const membersData = [
  {
    name: "John Smith",
    phoneNumber: "(123) 4567 9891",
    photo: photo,
    mail: "johnsmith@email.com",
    project: "Adidas",
    ledStatus: "Deal Unqualified",
    leadOwner: "Maria Rodriguez",
    photoOwner: photoW,
  },
  {
    name: "Emily Johnson",
    phoneNumber: "(234) 5678 9910",
    photo: photoW,
    mail: "emilyjohnson@email.com",
    project: "McDonald's",
    ledStatus: "Bad Timing",
    leadOwner: "John Perez",
    photoOwner: photo,
  },
  {
    name: "William Brown",
    phoneNumber: "(345) 6789 9123",
    photo: photo,
    mail: "williambrown@email.com",
    project: "Starbucks",
    ledStatus: "New",
    leadOwner: "Anna Martinez",
    photoOwner: photoW,
  },
  {
    name: "Olivia Davis",
    phoneNumber: "(456) 7891 9234",
    photo: photoW,
    mail: "oliviadavis@email.com",
    project: "Amazon",
    ledStatus: "Contracted",
    leadOwner: "Peter Gomez",
    photoOwner: photo,
  },
  {
    name: "James Wilson",
    phoneNumber: "(567) 8912 9345",
    photo: photo,
    mail: "jameswilson@email.com",
    project: "Google",
    ledStatus: "Deal Unqualified",
    leadOwner: "Laura Sanchez",
    photoOwner: photoW,
  },
  {
    name: "Sophia Martinez",
    phoneNumber: "(678) 9123 9456",
    photo: photoW,
    mail: "sophiamartinez@email.com",
    project: "Facebook",
    ledStatus: "Bad Timing",
    leadOwner: "Carlos Fernandez",
    photoOwner: photo,
  },
  {
    name: "Alexander Taylor",
    phoneNumber: "(789) 1234 9567",
    photo: photo,
    mail: "alexandertaylor@email.com",
    project: "Apple",
    ledStatus: "New",
    leadOwner: "Laura Sanchez",
    photoOwner: photoW,
  },
  {
    name: "Isabella Thomas",
    phoneNumber: "(891) 2345 9678",
    photo: photoW,
    mail: "isabellathomas@email.com",
    project: "Microsoft",
    ledStatus: "Contracted",
    leadOwner: "Diego Ramirez",
    photoOwner: photo,
  },
  {
    name: "Daniel Jackson",
    phoneNumber: "(912) 3456 9789",
    photo: photo,
    mail: "danieljackson@email.com",
    project: "Netflix",
    ledStatus: "Deal Unqualified",
    leadOwner: "Sofia Garcia",
    photoOwner: photoW,
  },
  {
    name: "Mia White",
    phoneNumber: "(123) 4567 9890",
    photo: photoW,
    mail: "miawhite@email.com",
    project: "Tesla",
    ledStatus: "Bad Timing",
    leadOwner: "Javier Hernandez",
    photoOwner: photo,
  },

  {
    name: "Emma Thompson",
    phoneNumber: "(234) 5678 9901",
    photo: photoW,
    mail: "emma.thompson@email.com",
    project: "IBM",
    ledStatus: "Deal Unqualified",
    leadOwner: "John Doe",
    photoOwner: photo,
  },
  {
    name: "Liam Wilson",
    phoneNumber: "(345) 6789 9012",
    photo: photo,
    mail: "liam.wilson@email.com",
    project: "Intel",
    ledStatus: "Bad Timing",
    leadOwner: "Jane Smith",
    photoOwner: photoW,
  },
  {
    name: "Ava Brown",
    phoneNumber: "(456) 7890 9123",
    photo: photoW,
    mail: "ava.brown@email.com",
    project: "Oracle",
    ledStatus: "New",
    leadOwner: "Michael Johnson",
    photoOwner: photo,
  },
  {
    name: "Noah Miller",
    phoneNumber: "(567) 8901 9234",
    photo: photo,
    mail: "noah.miller@email.com",
    project: "Samsung",
    ledStatus: "Contracted",
    leadOwner: "Sophia Davis",
    photoOwner: photoW,
  },
  {
    name: "Sophie Wilson",
    phoneNumber: "(678) 9012 9345",
    photo: photoW,
    mail: "sophie.wilson@email.com",
    project: "Sony",
    ledStatus: "Deal Unqualified",
    leadOwner: "James Taylor",
    photoOwner: photo,
  },
  {
    name: "Logan Taylor",
    phoneNumber: "(789) 0123 9456",
    photo: photo,
    mail: "logan.taylor@email.com",
    project: "Twitter",
    ledStatus: "Bad Timing",
    leadOwner: "Isabella Harris",
    photoOwner: photoW,
  },
  {
    name: "Harper Lee",
    phoneNumber: "(890) 1234 9567",
    photo: photoW,
    mail: "harper.lee@email.com",
    project: "Uber",
    ledStatus: "New",
    leadOwner: "Ethan Clark",
    photoOwner: photo,
  },
  {
    name: "William Clark",
    phoneNumber: "(901) 2345 9678",
    photo: photo,
    mail: "william.clark@email.com",
    project: "SpaceX",
    ledStatus: "Contracted",
    leadOwner: "Olivia Martinez",
    photoOwner: photoW,
  },
  {
    name: "Grace Baker",
    phoneNumber: "(123) 4567 9890",
    photo: photoW,
    mail: "grace.baker@email.com",
    project: "NASA",
    ledStatus: "Deal Unqualified",
    leadOwner: "Daniel White",
    photoOwner: photo,
  },
  {
    name: "Mason Adams",
    phoneNumber: "(987) 6543 9210",
    photo: photo,
    mail: "mason.adams@email.com",
    project: "Space Force",
    ledStatus: "Bad Timing",
    leadOwner: "Ella Cooper",
    photoOwner: photoW,
  },
  {
    name: "John Doe",
    phoneNumber: "(123) 4567 9890",
    photo: photo,
    mail: "johndoe@email.com",
    project: "Starbucks",
    ledStatus: "Good",
    leadOwner: "Jane Smith",
    photoOwner: photo,
  },
  {
    name: "Alice Williams",
    phoneNumber: "(987) 6543 9210",
    photo: photoW,
    mail: "alicewilliams@email.com",
    project: "Burger King",
    ledStatus: "Neutral",
    leadOwner: "Michael Johnson",
    photoOwner: photo,
  },
  {
    name: "Sarah Brown",
    phoneNumber: "(567) 8901 9234",
    photo: photoW,
    mail: "sarahbrown@email.com",
    project: "Wendy's",
    ledStatus: "Good Timing",
    leadOwner: "David Wilson",
    photoOwner: photo,
  },
  {
    name: "Robert Garcia",
    phoneNumber: "(876) 5432 9109",
    photo: photo,
    mail: "robertgarcia@email.com",
    project: "Subway",
    ledStatus: "Good Timing",
    leadOwner: "Emily Johnson",
    photoOwner: photoW,
  },
  {
    name: "Emma Thompson",
    phoneNumber: "(345) 6789 9012",
    photo: photoW,
    mail: "emmathompson@email.com",
    project: "KFC",
    ledStatus: "Good",
    leadOwner: "Alice Williams",
    photoOwner: photoW,
  },
];
